### ISSUE TITLE
ocpkg is missing a dependency for Flask or Flask-RESTful

### ISSUE THREAD

**Issue by cosmoharrigan** [opencog/ocpkg#12]
@githart:
Buildbot skips the unit test for the Python REST API because there is a dependency missing on the machine:
```
Failure: SkipTest (ImportError exception: make sure the required dependencies are installed.) ... SKIP: ImportError exception: make sure the required dependencies are installed.
```
(you can search for that string in [the logfile](http://buildbot.opencog.org:8010/builders/opencog_master/builds/563/steps/test/logs/testlog))

That means that ocpkg doesn't install all the required dependencies. Can you help add the missing dependency? It seems that it must be either **Flask** or **Flask-RESTful**:
https://github.com/opencog/opencog/blob/master/opencog/python/web/api/apimain.py#L3

You could check which one is missing:
```
sudo apt-get install python-pip
pip freeze
```

The unit test passes successfully locally. It would be helpful to have it pass on the Buildbot so that we can validate that new users who set up an environment using ocpkg will have all tests pass successfully.

**Comment by AmeBel** [comment]
closed b/c it has been resolved, for a while
