### ISSUE TITLE
unfound file in octool_rpi.sh

### ISSUE THREAD

**Issue by Kidist-Abraham** [opencog/ocpkg#121]
on download_install_oc () the .deb file of a cross complied open-cog is not  found on the server.

**Comment by Dagiopia** [comment]
The script checks if it's running on raspbian jessie or raspbian stretch and downloads a different deb package based on the release. I see that the stretch version doesn't exist on the server anymore (probably an accident during uodate). Will get it right up there soon.

**Comment by Dagiopia** [comment]
It's available now. I'll move everything to a ppa as soon as i'm back at the office
