### ISSUE TITLE
forcing cython=0.23 breaks python3

### ISSUE THREAD

**Issue by linas** [opencog/ocpkg#148]
This line: 
https://github.com/opencog/ocpkg/blob/8bde60792a78af6b9c10c67cad608fbf92d9d08a/ocpkg#L1009

breaks python3, see issue opencog/atomspace#2550

**Comment by AmeBel** [comment]
looking into it

**Comment by linas** [comment]
fixed in #149 .. thanks!

**Comment by AmeBel** [comment]
updated by https://github.com/opencog/ocpkg/pull/149 and test result https://circleci.com/workflow-run/568e7b4d-5d2a-496c-8954-6f856be20a3e
