### ISSUE TITLE
OpenSSL error on Ubuntu 20.04 LTS while installing

### ISSUE THREAD

**Issue by omar-3** [opencog/ocpkg#150]
I'm trying to install ```Link-Grammar``` using the command ```octool -rdcpav -l default``` that supposedly would install everything.

After build everything I guess, It starts to install ```Link-Grammar``` and that happens

```
[octool] Installing Link-Grammar....
--2020-06-13 10:09:36--  http://www.abisource.com/downloads/link-grammar/current/
Resolving www.abisource.com (www.abisource.com)... 130.89.149.216
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://www.abisource.com/downloads/link-grammar/current/ [following]
--2020-06-13 10:09:37--  https://www.abisource.com/downloads/link-grammar/current/
Connecting to www.abisource.com (www.abisource.com)|130.89.149.216|:443... connected.
OpenSSL: error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
Unable to establish SSL connection.
```

I asked on StackOverflow [here](https://stackoverflow.com/questions/62357205/openssl-cant-establish-ssl-connection-because-unsupported-protocol/62359497#62359497), but unfortunately, it didn't work.

What to do?

**Comment by linas** [comment]
See also https://github.com/opencog/link-grammar/issues/1098

**Comment by linas** [comment]
Closing, this was fixed a while ago.
