### ISSUE TITLE
Trying to build opencog, getting error /usr/bin/ld: cannot find -lserver

### ISSUE THREAD

**Issue by tarath** [opencog/ocpkg#44]
Hi,

I'm trying to do an initial build of opencog on a new docker system.

I have tried both using cmake and using the ocpkg.  The error happens immediately if I do ./octool -i, it happens midway through the build if I try and make opencog or if I do ./octool -b.  In all 3 cases I am getting an error like this:

Any help on what dependency is needed for lserver would be greatly appreciated.

make[2]: Entering directory `/home/opencog/opencog/build'
[ 40%] Building CXX object opencog/attention/CMakeFiles/attention.dir/AttentionModule.cc.o
[ 40%] Building CXX object opencog/attention/CMakeFiles/attention.dir/ForgettingAgent.cc.o
[ 41%] Building CXX object opencog/attention/CMakeFiles/attention.dir/HebbianUpdatingAgent.cc.o
[ 43%] Building CXX object opencog/attention/CMakeFiles/attention.dir/SimpleHebbianUpdatingAgent.cc.o
[ 43%] Building CXX object opencog/attention/CMakeFiles/attention.dir/ImportanceSpreadingAgent.cc.o
[ 45%] Building CXX object opencog/attention/CMakeFiles/attention.dir/ImportanceDiffusionAgent.cc.o
[ 45%] Building CXX object opencog/attention/CMakeFiles/attention.dir/SimpleImportanceDiffusionAgent.cc.o
[ 46%] Building CXX object opencog/attention/CMakeFiles/attention.dir/ImportanceUpdatingAgent.cc.o
Linking CXX shared library libattention.so
/usr/bin/ld: cannot find -lserver
collect2: error: ld returned 1 exit status
make[2]: *** [opencog/attention/libattention.so] Error 1
make[2]: Leaving directory `/home/opencog/opencog/build'
make[1]: *** [opencog/attention/CMakeFiles/attention.dir/all] Error 2
make[1]: Leaving directory `/home/opencog/opencog/build'
make: *** [all] Error 2
make: Leaving directory `/home/opencog/opencog/build'

**Comment by AmeBel** [comment]
Hi,

have you tried following https://github.com/opencog/docker/blob/master/opencog/README.md?

**Comment by tarath** [comment]
I followed these steps here:
http://wiki.opencog.org/w/Building_OpenCog#Docker_.2864_bit_systems_only.29

I see the instructions you referred to are different but it sounds like
they may not work from windows.  I am using the Docker quickstart terminal
on windows 10.  I am quite new to docker.

Should I try follow the instructions you linked to or do I need to wait for
an updated list of instructions with windows specific commands?

**Comment by linas** [comment]
this may be do to a re-organization of the directories I did just a few hours ago.  Try `git pull` again, or, by hand, apply this patch:
```
--- a/opencog/CMakeLists.txt
+++ b/opencog/CMakeLists.txt
@@ -14,8 +14,9 @@ IF (HAVE_ATOMSPACE)
 ENDIF (HAVE_ATOMSPACE)
 
 IF (HAVE_SERVER)
-       ADD_SUBDIRECTORY (attention)
        ADD_SUBDIRECTORY (cogserver)
+       # attention builds *after* cogserver.
+       ADD_SUBDIRECTORY (attention)
        # Octomap checking will be done inside
        # Will always build types
        ADD_SUBDIRECTORY (spacetime)
```

**Comment by tarath** [comment]
@Linas, Unfortunately that doesn't seem to be working for me, getting the
same issues.

@Amen, I managed to get docker-compose working sort of on windows but it
doesn't support interactive mode and I'm not sure how to actually write
code and run the tests without that.  For reference I installed
docker-compose using this: docker build -t docker-compose
github.com/docker/compose.  It appears their latest release candidate does
support windows (but without some of the features).

Again I really appreciate the help guys, if you have any other suggestions
please let me know.

**Comment by AmeBel** [comment]
yes, just followed https://docs.docker.com/engine/installation/windows/#using-the-docker-quickstart-terminal and got the same `doesn't support interactive ` thingy. I will add a script for windows that should do the same thing that docker compose dose.

**Comment by linas** [comment]
Odd.  Once you get a working command line, then verify that the directory `build/opencog/cogserver/server` contains a file `libserver.so`  this is what cmake should be finding and using.

**Comment by tarath** [comment]
Hmm it appears my build/opencog/cogserver directory doesn't even have a
server subdirectory.

All it contains is a CMakeFiles directory, cmake_install.cmake and
Makefile.  Am I building things in the wrong order somehow?

**Comment by AmeBel** [comment]
@tarath just added a script for windows https://github.com/opencog/docker/pull/62 and also updated the instruction in the README. Try it out and let me know

**Comment by linas** [comment]
When you say `cmake ..`  it says `The following components will be built:` is the server listed among them?

**Comment by tarath** [comment]
@Amen, I am running into a kernel issue that is preventing me from
installing the relex component which is documented here:
https://github.com/docker/docker/issues/18180#issuecomment-167042078 so
need to resolve that before I can continue testing the docker script.  It
only occurs when I run the docker build script with -r but that seems to be
required for the windows script to work (otherwise relex is not found) and
I get "Error response from daemon: no such id: relex" which makes sense of
course.

**Comment by tarath** [comment]
@Linas

Yes the server is listed.  See the cmake output below.

The following components will be built:
-----------------------------------------------
   Attention        - Agents for attention allocation dynamics.
   Blopex           - BLOPEX block eigenvalue solver.
   Cython bindings  - Cython (python) bindings.
   Dim. Embedding   - Compute dimensional embedding of the AtomSpace.
   Python tests     - Python bindings nose tests.
   REST             - REST Atomspace Publisher module.
   Server           - The CogServer.
   Spatial          - Vizualisation of the 3D spacemap.
   Unit tests       - Unit tests.
   Viterbi          - Viterbi Parser for Link Grammar.

The following components WILL NOT be built:
-----------------------------------------------
   Doxygen          - Code documentation.
   GTK Visualizer   - GTK3-based Atomspace Visualizer.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/opencog/opencog/build

**Comment by linas** [comment]
I believe this fixes it: https://github.com/opencog/opencog/pull/1965

**Comment by tarath** [comment]
I believe this worked, thanks
