### ISSUE TITLE
missing packages

### ISSUE THREAD

**Issue by edpell** [opencog/ocpkg#61]
I tried ./octool -rdpcalv and got these two missing messages

http://ppa.launchpad.net/opencog-dev/ppa/ubuntu/dists/main/binary-amd64/Packages
http://ppa.launchpad.net/opencog-dev/ppa/ubuntu/dists/main/binary-i386/Packages

I then tried
https://github.com/opencog/opencog/blob/master/scripts/ocpkg
it also was not found. 

Any guidance is appreciated. Thanks.

**Comment by linas** [comment]
I think you need to get it from here: https://github.com/opencog/ocpkg/
 Nil and Amen maintain this tool, they'll know more.

--linas

**Comment by AmeBel** [comment]
What is your ubuntu version?

**Comment by AmeBel** [comment]
Made some cleanups. Follow the instruction @ http://wiki.opencog.org/wikihome/index.php/Building_OpenCog#octool_for_ubuntu and let us know if you still have an issue.

**Comment by linas** [comment]
closing, I think this is resolved.
