### ISSUE TITLE
what is libjson-spirit-dev needed for?

### ISSUE THREAD

**Issue by linas** [opencog/ocpkg#70]
Ubuntu xenial doesn't have it.  As best as I can tell, its not needed for anything, but I am not quite sure ... 

I suspect that this is a left-over from the old embodiment code ...  but maybe its also used elsewhere, e.g by ZMQ?

**Comment by AmeBel** [comment]
It might not be need as it has been vendored in https://github.com/opencog/opencog/tree/master/lib/json_spirit
