### ISSUE TITLE
hard-coded gcc version

### ISSUE THREAD

**Issue by linas** [opencog/ocpkg#72]
I've been using gcc-4.8 (the default) on trusty, since forever.  Thus I was surprised to see this hard-coded:

```
        g++-4.6 \
        gcc-4.6 \
        libstdc++6-4.6-dev \
```

The above prevent octool from working on Ubuntu xenial.  Its enough to just install g++ and gcc  -- and I am not convinced that libstdc++ needs to be specified; the correct version seems to get installed, automatically.

**Comment by linas** [comment]
Also, there is a line 
```
CXX=g++-4.8 cmake .. -DCMAKE_BUILD_TYPE=Release
```
The explicit call to 4.8 is not needed.  Also -- if above is asking for 4.8, then why was 4.6 installed ??

**Comment by AmeBel** [comment]
It is not installed. It used to be used by the option to create cogbuntu, that is not maintained anymore.

**Comment by AmeBel** [comment]
build-essential is used https://github.com/opencog/ocpkg/blob/master/ocpkg#L125

**Comment by linas** [comment]
Sure it is: right here:
https://github.com/opencog/ocpkg/blob/master/ocpkg#L286-L287
and here:
https://github.com/opencog/ocpkg/blob/master/ocpkg#L306

These lead to an explicit crash

**Comment by linas** [comment]
Oh, I see -- strange `PACKAGES_EXDEV` is used only to remove the packages.  However, hrtool crashes at that location, and the work-around is to hack on ocpkg (aka octool in hrtool)  -- I don't understand why its crashing, because the purge should be harmless ....

**Comment by AmeBel** [comment]
and the purge isn't called unless you are using one of the modes

**Comment by AmeBel** [comment]
Are you trying on ubuntu xenial? I haven't tested on that

**Comment by AmeBel** [comment]
Testing on 16.04 now.

**Comment by linas** [comment]
Seems that xenial works great for cogutils, atomspace, opencog.  Am trying to test the rest of the hr stack, now.

**Comment by linas** [comment]
link-gramar will have to bump to a new version to support java jdk9

**Comment by linas** [comment]
I assume this is no longer an issue
