### ISSUE TITLE
binutils-dev needed for stack-trace printing

### ISSUE THREAD

**Issue by linas** [opencog/ocpkg#73]
Opencog won't print a stack trace, when it crashes, if binutils-dev is not installed.  From what I can tell .. its not installed anywhere by ocpkg.

**Comment by AmeBel** [comment]
Installed @ https://github.com/opencog/ocpkg/blob/master/ocpkg#L149

**Comment by linas** [comment]
OK. Indeed. That's very strange, maybe if failed to install -- hrtool did not report any errors, but cogutils was built without the stack trace parts.  I just checked now, and it is installed, so I can't explain the original error.

**Comment by AmeBel** [comment]
I got why that is occurring. Fixed in https://github.com/opencog/ocpkg/pull/75

Purge binutils-dev and reinstall binutils-dev, to get StackPrint feature to build in cogutils.

**Comment by linas** [comment]
thanks!

**Comment by linas** [comment]
I mean, thanks, all this kind of hacking is ugly and nasty but is important, and so much appreciated!
