### ISSUE TITLE
missing octo dependencies in ocpkg for ubuntu 16.04

### ISSUE THREAD

**Issue by mjsduncan** [opencog/ocpkg#87]
this may have been fixed with last ocpkg edit but when i ran ./octool -i it installed ros-lunar-octomap package and i had to install liboctomap-dev with dependency liboctomap1.6v5 to get cmake/make to build Spatial and SpaceTime.  and then the associated unit tests fail:
```
	  2 - AtomSpacePublisherModuleUTest (OTHER_FAULT)
	 17 - AtomOcTreeUTest (SEGFAULT)
	 18 - TimeSpaceAtomUTest (SEGFAULT)
	 19 - AnaphoraTest (Failed)
	 22 - ChatlangUTest (Failed)
	 23 - MOSESPLNSynergyUTest (Failed)
	 31 - CythonSpatial (Failed)
	 32 - CythonSpacetime (SEGFAULT)
	 37 - PatternMinerUTest (Failed)
Errors while running CTest
````
what is the correct dependency?

**Comment by AmeBel** [comment]
I tested it with both liboctomap-dev and ros-lunar-octomap(after updating FindOctomap.cmake) and the set of tests that fail are the same, with the exception of AtomOcTreeUTest.

**Comment by mjsduncan** [comment]
thanks, amen!  so does that mean all those tests are failing for current opencog/master build?
also, i noticed the current liboctomap-dev version is 1.6.8 and the lib-indigo-octomap version in the hanson dependencies is 1.6.9 , could that be causing the test failures (assuming the hanson stack is passing the octomap related tests)?

**Comment by AmeBel** [comment]
The lists of tests that are failing are http://61.92.69.39:8080/job/ci-opencog-master/942/console.

**Comment by mjsduncan** [comment]
thanks!  i wish i'd known about that earlier, i wouldn't have spent so much time trying to figure out what i was doing wrong trying to build stuff :P

**Comment by linas** [comment]
AnaphoraTest *always* passes for me.

**Comment by linas** [comment]
The full set of differences, for me, from Mike's and Amen's results:

AtomOcTreeUTest always passes for me
AnaphoraTest always passes for me.

TemporalTableUTest always fails for me
PLNRulesUTest always fails for me
OpenPsiUTest always fails for me

**Comment by linas** [comment]
It would be nice if things got fixed so that all tests passed.

**Comment by mjsduncan** [comment]
linus, could the octomap dependent code be failing because of version mismatch?  the current ubuntu 16.04 repo installs ros-lunar-octomap 1.9.0 which doesn't build, and has liboctomap-dev 1.6.8, which builds but fails unit testing.   the hanson stack installs ros-indigo-octomap 1.6.9

**Comment by linas** [comment]
not sure. Last time I tried, everything built just fine on xenial, (without ros installed) but it's been a while since I tried that. I'll try again.

**Comment by linas** [comment]
Unclear. My xenial container installs ROS karmic, not lunar. It does build, but I can't run unit tests, because I don't have cxxtest in that container.

The octomap API is rapidly changing in non-backwards-compatible ways, and @yantrabuddhi is not here to maintain it.

**Comment by linas** [comment]
p.s. PLNRulesUTet only sometimes fails for me. It failed this morning, but passed this afternoon. Not sure what's up with that.

**Comment by linas** [comment]
https://github.com/opencog/opencog/issues/2546
