### ISSUE TITLE
Need newer version of guile

### ISSUE THREAD

**Issue by linas** [opencog/ocpkg#9]
Currently, ocpkg calls for guile-1.8.8 to be installed; its probably time to move to guile-2.0.5 or newer (guile 2.0 is now 4 years old, and should be widely available; version 2.0.5 is what's on ubuntu precise 12.04 LTS)

Anyway, I'd recently fixed some UTF-8 bugs in one of the nlp scirpts, which requires rnrs which is provided by:

guile-2.0-libs: /usr/share/guile/2.0/rnrs

rnrs implements the r5rs and r6rs scheme standards.  It doesn't exist in guile-1.8

**Comment by AmeBel** [comment]
closed b/c it has been resolved, for a while.
