### ISSUE TITLE
ocpkg should include a dependency for a jdk package

### ISSUE THREAD

**Issue by edoubt** [opencog/ocpkg#96]
Nils asked me to file an issue here, so I'm complying. I attempted to use ocpkg to install opencog on an ubuntu 16.04 VM and it failed with the following error:

BUILD FAILED
/tmp/link-grammar-5.4.2/build/bindings/java/build.xml:21: Unable to
find a javac compiler; com.sun.tools.javac.Main is not on the classpath.
Perhaps JAVA_HOME does not point to the JDK.
It is currently set to "/usr/lib/jvm/java-8-openjdk-amd64/jre"

Total time: 0 seconds
Makefile:588: recipe for target 'linkgrammar-5.4.2.jar' failed
make[2]: *** [linkgrammar-5.4.2.jar] Error 1
make[2]: Leaving directory '/tmp/link-grammar-5.4.2/build/bindings/java'
Makefile:438: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/link-grammar-5.4.2/build/bindings'
Makefile:535: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

After manually installing the openjdk-8-jdk package the install appeared to successfully complete. There may be alternative jdk packages available in ubuntu that would also satisfy this dependency though.

      best,
           ~c

**Comment by AmeBel** [comment]
Fixed by https://github.com/opencog/ocpkg/pull/101
